title = 'IS-LAN'
baseURL = 'https://islan.nl/'
languageCode = 'nl-nl'
defaultContentLanguage = 'nl'

theme = 'ananke'
enableGitInfo = true
paginate = 10
summaryLength = 70
#SectionPagesMenu = "main"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  title = 'Posts'
  url = '/posts/'
  weight = -110
 [[menu.main]]
  identifier = 'servers'
  name = 'Servers'
  title = 'servers'
  url = '/servers/'
  weight = -100

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  mainSections = ["posts"]
  custom_css = ["custom.css"]